modmap:
  - name: basic_modmap
    remap:
      alt_r: ctrl_l
      ctrl_l: esc
      shift_r: enter
      enter: backspace
      ctrl_r: grave

keymap:
  - name: nav_keys
    remap:
      alt-h: left
      alt-j: down
      alt-k: up
      alt-l: right

